[package]
version = "1.0.0"
title = "Vehicle Path Tracking Extension"
description="Allows omni.physxvehicle to move along a user-defined trajectory via path tracking 'pure pursuit' inspired algorithm."
readme  = "docs/index.rst"
changelog="docs/CHANGELOG.md"
repository = ""
icon = "data/icon.png"
preview_image="data/preview.png"
keywords = ["kit", "omni.physxvehicle", "animation", "path", "tracking", "vehicle"]

[dependencies]
"omni.kit.uiapp" = {}

[[python.module]]
name = "omni.path_tracking"