[package]
version = "1.0.1-beta"
title = "Vehicle Path Tracking Extension"
description="Allows omni.physxvehicle to move along a user-defined trajectory via path tracking 'pure pursuit' inspired algorithm."
readme  = "docs/index.rst"
changelog="docs/CHANGELOG.md"
repository = ""
icon = "data/icon.png"
preview_image="data/preview.png"
keywords = ["kit", "omni.physxvehicle", "animation", "path", "tracking", "vehicle"]

[dependencies]
"omni.usd" = {}
"omni.kit.uiapp" = {}
"omni.physx" = {}
"omni.physx.ui" = {}
"omni.physx.vehicle" = {}
"omni.usdphysics" = {}
"omni.physx.commands"  = {}
"omni.kit.test_suite.helpers" = {}

[[python.module]]
name = "ext.path.tracking"

[[test]]
args = [
    "--/renderer/enabled=pxr",
    "--/renderer/active=pxr",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]

dependencies = [
    "omni.hydra.pxr",
    "omni.kit.mainwindow",
    "omni.kit.widget.stage",
    "omni.kit.window.viewport",
    "omni.kit.window.stage",
    "omni.kit.window.console",
    "omni.kit.test_suite.helpers",
]